var annotated =
[
    [ "__FILE", "struct_____f_i_l_e.html", "struct_____f_i_l_e" ],
    [ "TM_AM2301_Data_t", "struct_t_m___a_m2301___data__t.html", "struct_t_m___a_m2301___data__t" ],
    [ "TM_BMP180_t", "struct_t_m___b_m_p180__t.html", "struct_t_m___b_m_p180__t" ],
    [ "TM_DMA2DRAPHIC_Poly_t", "struct_t_m___d_m_a2_d_r_a_p_h_i_c___poly__t.html", "struct_t_m___d_m_a2_d_r_a_p_h_i_c___poly__t" ],
    [ "TM_DS1307_Time_t", "struct_t_m___d_s1307___time__t.html", "struct_t_m___d_s1307___time__t" ],
    [ "TM_ETHERNET_t", "struct_t_m___e_t_h_e_r_n_e_t__t.html", "struct_t_m___e_t_h_e_r_n_e_t__t" ],
    [ "TM_ETHERNETPOST_t", "struct_t_m___e_t_h_e_r_n_e_t_p_o_s_t__t.html", "struct_t_m___e_t_h_e_r_n_e_t_p_o_s_t__t" ],
    [ "TM_FontDef_t", "struct_t_m___font_def__t.html", "struct_t_m___font_def__t" ],
    [ "TM_GPS_Data_t", "struct_t_m___g_p_s___data__t.html", "struct_t_m___g_p_s___data__t" ],
    [ "TM_GPS_Date_t", "struct_t_m___g_p_s___date__t.html", "struct_t_m___g_p_s___date__t" ],
    [ "TM_GPS_Distance_t", "struct_t_m___g_p_s___distance__t.html", "struct_t_m___g_p_s___distance__t" ],
    [ "TM_GPS_Float_t", "struct_t_m___g_p_s___float__t.html", "struct_t_m___g_p_s___float__t" ],
    [ "TM_GPS_Time_t", "struct_t_m___g_p_s___time__t.html", "struct_t_m___g_p_s___time__t" ],
    [ "TM_HCSR04_t", "struct_t_m___h_c_s_r04__t.html", "struct_t_m___h_c_s_r04__t" ],
    [ "TM_ILI931_Options_t", "struct_t_m___i_l_i931___options__t.html", "struct_t_m___i_l_i931___options__t" ],
    [ "TM_ILI9341_Button_t", "struct_t_m___i_l_i9341___button__t.html", "struct_t_m___i_l_i9341___button__t" ],
    [ "TM_L3GD20_t", "struct_t_m___l3_g_d20__t.html", "struct_t_m___l3_g_d20__t" ],
    [ "TM_LIS302DL_LIS3DSH_t", "struct_t_m___l_i_s302_d_l___l_i_s3_d_s_h__t.html", "struct_t_m___l_i_s302_d_l___l_i_s3_d_s_h__t" ],
    [ "TM_MPU6050_t", "struct_t_m___m_p_u6050__t.html", "struct_t_m___m_p_u6050__t" ],
    [ "TM_OneWire_t", "struct_t_m___one_wire__t.html", "struct_t_m___one_wire__t" ],
    [ "TM_PWM_TIM_t", "struct_t_m___p_w_m___t_i_m__t.html", "struct_t_m___p_w_m___t_i_m__t" ],
    [ "TM_PWMIN_t", "struct_t_m___p_w_m_i_n__t.html", "struct_t_m___p_w_m_i_n__t" ],
    [ "TM_RE_t", "struct_t_m___r_e__t.html", "struct_t_m___r_e__t" ],
    [ "TM_RTC_AlarmTime_t", "struct_t_m___r_t_c___alarm_time__t.html", "struct_t_m___r_t_c___alarm_time__t" ],
    [ "TM_RTC_t", "struct_t_m___r_t_c__t.html", "struct_t_m___r_t_c__t" ],
    [ "TM_SERVO_t", "struct_t_m___s_e_r_v_o__t.html", "struct_t_m___s_e_r_v_o__t" ],
    [ "TM_STMPE811_TouchData", "struct_t_m___s_t_m_p_e811___touch_data.html", "struct_t_m___s_t_m_p_e811___touch_data" ],
    [ "TM_TCPCLIENT_t", "struct_t_m___t_c_p_c_l_i_e_n_t__t.html", "struct_t_m___t_c_p_c_l_i_e_n_t__t" ],
    [ "TM_TIMER_PROPERTIES_t", "struct_t_m___t_i_m_e_r___p_r_o_p_e_r_t_i_e_s__t.html", "struct_t_m___t_i_m_e_r___p_r_o_p_e_r_t_i_e_s__t" ],
    [ "TM_USB_HIDDEVICE_Gamepad_t", "struct_t_m___u_s_b___h_i_d_d_e_v_i_c_e___gamepad__t.html", "struct_t_m___u_s_b___h_i_d_d_e_v_i_c_e___gamepad__t" ],
    [ "TM_USB_HIDDEVICE_Keyboard_t", "struct_t_m___u_s_b___h_i_d_d_e_v_i_c_e___keyboard__t.html", "struct_t_m___u_s_b___h_i_d_d_e_v_i_c_e___keyboard__t" ],
    [ "TM_USB_HIDDEVICE_Mouse_t", "struct_t_m___u_s_b___h_i_d_d_e_v_i_c_e___mouse__t.html", "struct_t_m___u_s_b___h_i_d_d_e_v_i_c_e___mouse__t" ],
    [ "TM_USB_HIDHOST_Keyboard_t", "struct_t_m___u_s_b___h_i_d_h_o_s_t___keyboard__t.html", "struct_t_m___u_s_b___h_i_d_h_o_s_t___keyboard__t" ],
    [ "TM_USB_HIDHOST_Mouse_t", "struct_t_m___u_s_b___h_i_d_h_o_s_t___mouse__t.html", "struct_t_m___u_s_b___h_i_d_h_o_s_t___mouse__t" ],
    [ "TM_USB_VCP_Settings_t", "struct_t_m___u_s_b___v_c_p___settings__t.html", "struct_t_m___u_s_b___v_c_p___settings__t" ]
];