.TH "__FILE" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
__FILE \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_stdio\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int(* \fBoutputFuncPointer\fP )(int, FILE *)"
.br
.ti -1c
.RI "int(* \fBinputFuncPointer\fP )(FILE *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library dependencies
.IP "\(bu" 2
STM32F4xx
.IP "\(bu" 2
defines\&.h
.IP "\(bu" 2
\fBattributes\&.h\fP
.IP "\(bu" 2
stdio\&.h Includes File structure for stdio stream output
.PP
.PP
Parameters:
.IP "\(bu" 2
int (*outputFuncPointer)(int, FILE *): Pointer to function to call when need to output data to stream
.IP "\(bu" 2
int (*inputFuncPointer)(FILE *): Pointer to function to call when trying to get data from stream 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
