.TH "TM_BMP180_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_BMP180_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_bmp180\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBAltitude\fP"
.br
.ti -1c
.RI "uint32_t \fBPressure\fP"
.br
.ti -1c
.RI "float \fBTemperature\fP"
.br
.ti -1c
.RI "uint16_t \fBDelay\fP"
.br
.ti -1c
.RI "TM_BMP180_Oversampling_t \fBOversampling\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
BMP180 working struct
.PP
Parameters:
.IP "\(bu" 2
float Altitude: Calculated altitude at given read pressure
.IP "\(bu" 2
uint32_t Pressure: Pressure in pascals
.IP "\(bu" 2
float Temperature: Temperature in degrees
.IP "\(bu" 2
uint16_t Delay: Number of microseconds, that sensor needs to calculate data that you request to
.IP "\(bu" 2
TM_BMP180_Oversampling_t Oversampling: Oversampling for pressure calculation 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
