.TH "TM_DMA2DRAPHIC_Poly_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_DMA2DRAPHIC_Poly_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_dma2d_graphic\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBX\fP"
.br
.ti -1c
.RI "uint16_t \fBY\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for polygon line
.PP
Parameters:
.IP "\(bu" 2
uint16_t X: X coordinate for poly line
.IP "\(bu" 2
uint16_t Y: Y coordinate for poly line 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
