.TH "TM_ETHERNET_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_ETHERNET_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBip_addr\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBmac_addr\fP [6]"
.br
.ti -1c
.RI "uint8_t \fBnetmask\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBgateway\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBstaticip\fP"
.br
.ti -1c
.RI "uint8_t \fBip_is_set\fP"
.br
.ti -1c
.RI "uint8_t \fBlink_is_up\fP"
.br
.ti -1c
.RI "uint32_t \fBClientSuccessfullConnections\fP"
.br
.ti -1c
.RI "uint32_t \fBClientConnections\fP"
.br
.ti -1c
.RI "uint64_t \fBClient_TX_Bytes\fP"
.br
.ti -1c
.RI "uint64_t \fBClient_RX_Bytes\fP"
.br
.ti -1c
.RI "uint32_t \fBServer_Connections\fP"
.br
.ti -1c
.RI "uint64_t \fBServer_TX_Bytes\fP"
.br
.ti -1c
.RI "uint64_t \fBServer_RX_Bytes\fP"
.br
.ti -1c
.RI "uint8_t \fBserver_active\fP"
.br
.ti -1c
.RI "uint16_t \fBserver_port\fP"
.br
.ti -1c
.RI "uint8_t \fBspeed_100m\fP"
.br
.ti -1c
.RI "uint8_t \fBfull_duplex\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
