.TH "TM_ESP8266_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_ESP8266_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBConnections\fP"
.br
.ti -1c
.RI "uint8_t \fBMultiConnections\fP"
.br
.ti -1c
.RI "uint32_t \fBIncomingBytes\fP [5]"
.br
.ti -1c
.RI "char \fBRequest\fP [5][ESP8266_REQUEST_BUFFER_LEN]"
.br
.ti -1c
.RI "uint8_t \fBAPIP\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBSTAIP\fP [4]"
.br
.ti -1c
.RI "uint8_t \fBAPMAC\fP [6]"
.br
.ti -1c
.RI "uint8_t \fBSTAMAC\fP [6]"
.br
.ti -1c
.RI "uint32_t \fBBaudrate\fP"
.br
.ti -1c
.RI "TM_ESP8266_Result_t \fBStatus\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
