.TH "TM_FontDef_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_FontDef_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_fonts\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBFontWidth\fP"
.br
.ti -1c
.RI "uint8_t \fBFontHeight\fP"
.br
.ti -1c
.RI "const uint16_t * \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
|---------------------------------------------------------------------- | Copyright (C) Tilen Majerle, 2014 | | This program is free software: you can redistribute it and/or modify | it under the terms of the GNU General Public License as published by | the Free Software Foundation, either version 3 of the License, or | any later version\&. | | This program is distributed in the hope that it will be useful, | but WITHOUT ANY WARRANTY; without even the implied warranty of | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the | GNU General Public License for more details\&. | | You should have received a copy of the GNU General Public License | along with this program\&. If not, see http://www.gnu.org/licenses/\&. |---------------------------------------------------------------------- Fonts library Font struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
