.TH "TM_GPS_Macros" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPS_Macros \- TM_GPS_Macros
.PP
Library private defines without any sense for USER\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPS_IS_DIGIT\fP(x)   ((x) >= '0' && (x) <= '9')"
.br
.ti -1c
.RI "#define \fBGPS_C2N\fP(a)   (((a) - 48))"
.br
.ti -1c
.RI "#define \fBGPS_C2NM\fP(a,  x)   C2N(a) * (x)"
.br
.ti -1c
.RI "#define \fBGPS_CONCAT\fP(x,  y)   ((x) << 5 | (y))"
.br
.ti -1c
.RI "#define \fBGPS_GPGGA\fP   0"
.br
.ti -1c
.RI "#define \fBGPS_GPRMC\fP   1"
.br
.ti -1c
.RI "#define \fBGPS_GPGSA\fP   2"
.br
.ti -1c
.RI "#define \fBGPS_GPGSV\fP   3"
.br
.ti -1c
.RI "#define \fBGPS_ERR\fP   4"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_LATITUDE\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_LONGITUDE\fP   0x00000002"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_SATS\fP   0x00000004"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_FIX\fP   0x00000008"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_ALTITUDE\fP   0x00000010"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_EW\fP   0x00000020"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_NS\fP   0x00000040"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_TIME\fP   0x00000080"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_SPEED\fP   0x00000100"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_DATE\fP   0x00000200"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_VALIDITY\fP   0x00000400"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_DIRECTION\fP   0x00008000"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_HDOP\fP   0x00000800"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_VDOP\fP   0x00001000"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_PDOP\fP   0x00002000"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_FIXMODE\fP   0x00004000"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_SATS1_12\fP   0x00020000"
.br
.ti -1c
.RI "#define \fBGPS_FLAG_SATSINVIEW\fP   0x00010000"
.br
.ti -1c
.RI "#define \fBGPS_POS_LATITUDE\fP   GPS_CONCAT(GPS_GPGGA, 2)"
.br
.ti -1c
.RI "#define \fBGPS_POS_LONGITUDE\fP   GPS_CONCAT(GPS_GPGGA, 4)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SATS\fP   GPS_CONCAT(GPS_GPGGA, 7)"
.br
.ti -1c
.RI "#define \fBGPS_POS_FIX\fP   GPS_CONCAT(GPS_GPGGA, 6)"
.br
.ti -1c
.RI "#define \fBGPS_POS_ALTITUDE\fP   GPS_CONCAT(GPS_GPGGA, 9)"
.br
.ti -1c
.RI "#define \fBGPS_POS_TIME\fP   GPS_CONCAT(GPS_GPGGA, 1)"
.br
.ti -1c
.RI "#define \fBGPS_POS_EW\fP   GPS_CONCAT(GPS_GPGGA, 5)"
.br
.ti -1c
.RI "#define \fBGPS_POS_NS\fP   GPS_CONCAT(GPS_GPGGA, 3)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SPEED\fP   GPS_CONCAT(GPS_GPRMC, 7)"
.br
.ti -1c
.RI "#define \fBGPS_POS_DATE\fP   GPS_CONCAT(GPS_GPRMC, 9)"
.br
.ti -1c
.RI "#define \fBGPS_POS_VALIDITY\fP   GPS_CONCAT(GPS_GPRMC, 2)"
.br
.ti -1c
.RI "#define \fBGPS_POS_DIRECTION\fP   GPS_CONCAT(GPS_GPRMC, 8)"
.br
.ti -1c
.RI "#define \fBGPS_POS_PDOP\fP   GPS_CONCAT(GPS_GPGSA, 15)"
.br
.ti -1c
.RI "#define \fBGPS_POS_HDOP\fP   GPS_CONCAT(GPS_GPGSA, 16)"
.br
.ti -1c
.RI "#define \fBGPS_POS_VDOP\fP   GPS_CONCAT(GPS_GPGSA, 17)"
.br
.ti -1c
.RI "#define \fBGPS_POS_FIXMODE\fP   GPS_CONCAT(GPS_GPGSA, 2)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT1\fP   GPS_CONCAT(GPS_GPGSA, 3)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT2\fP   GPS_CONCAT(GPS_GPGSA, 4)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT3\fP   GPS_CONCAT(GPS_GPGSA, 5)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT4\fP   GPS_CONCAT(GPS_GPGSA, 6)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT5\fP   GPS_CONCAT(GPS_GPGSA, 7)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT6\fP   GPS_CONCAT(GPS_GPGSA, 8)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT7\fP   GPS_CONCAT(GPS_GPGSA, 9)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT8\fP   GPS_CONCAT(GPS_GPGSA, 10)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT9\fP   GPS_CONCAT(GPS_GPGSA, 11)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT10\fP   GPS_CONCAT(GPS_GPGSA, 12)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT11\fP   GPS_CONCAT(GPS_GPGSA, 13)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SAT12\fP   GPS_CONCAT(GPS_GPGSA, 14)"
.br
.ti -1c
.RI "#define \fBGPS_POS_SATSINVIEW\fP   GPS_CONCAT(GPS_GPGSV, 3)"
.br
.ti -1c
.RI "#define \fBGPS_EARTH_RADIUS\fP   6371"
.br
.ti -1c
.RI "#define \fBGPS_DEGREES2RADIANS\fP(x)   ((x) * (float)0\&.01745329251994)"
.br
.ti -1c
.RI "#define \fBGPS_RADIANS2DEGREES\fP(x)   ((x) * (float)57\&.29577951308232)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library private defines without any sense for USER\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
