.TH "TM_GPS_Typedefs" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPS_Typedefs \- TM_GPS_Typedefs
.PP
Library Typedefs\&.  

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTM_GPS_Float_t\fP"
.br
.RI "\fIGPS float structure\&. \fP"
.ti -1c
.RI "struct \fBTM_GPS_Date_t\fP"
.br
.RI "\fIDate struct for GPS date\&. \fP"
.ti -1c
.RI "struct \fBTM_GPS_Time_t\fP"
.br
.RI "\fITime structure for GPS\&. \fP"
.ti -1c
.RI "struct \fBTM_GPS_Data_t\fP"
.br
.RI "\fIMain GPS data structure\&. \fP"
.ti -1c
.RI "struct \fBTM_GPS_Distance_t\fP"
.br
.RI "\fIGPS Distance and bearing struct\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTM_GPS_Result_t\fP { \fBTM_GPS_Result_NewData\fP, \fBTM_GPS_Result_OldData\fP, \fBTM_GPS_Result_FirstDataWaiting\fP }"
.br
.RI "\fIGPS Result enumeration\&. \fP"
.ti -1c
.RI "enum \fBTM_GPS_Speed_t\fP { \fBTM_GPS_Speed_KilometerPerSecond\fP, \fBTM_GPS_Speed_MeterPerSecond\fP, \fBTM_GPS_Speed_KilometerPerHour\fP, \fBTM_GPS_Speed_MeterPerMinute\fP, \fBTM_GPS_Speed_MilePerSecond\fP, \fBTM_GPS_Speed_MilePerHour\fP, \fBTM_GPS_Speed_FootPerSecond\fP, \fBTM_GPS_Speed_FootPerMinute\fP, \fBTM_GPS_Speed_MinutePerKilometer\fP, \fBTM_GPS_Speed_SecondPerKilometer\fP, \fBTM_GPS_Speed_SecondPer100Meters\fP, \fBTM_GPS_Speed_MinutePerMile\fP, \fBTM_GPS_Speed_SecondPerMile\fP, \fBTM_GPS_Speed_SecondPer100Yards\fP, \fBTM_GPS_Speed_SeaMilePerHour\fP }"
.br
.RI "\fISpeed conversion enumeration\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Library Typedefs\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTM_GPS_Result_t\fP"

.PP
GPS Result enumeration\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_GPS_Result_NewData \fP\fP
New data are available to operate with 
.TP
\fB\fITM_GPS_Result_OldData \fP\fP
We don't have new data available yet 
.TP
\fB\fITM_GPS_Result_FirstDataWaiting \fP\fP
We are waiting for first data from GPS module 
.SS "enum \fBTM_GPS_Speed_t\fP"

.PP
Speed conversion enumeration\&. 
.PP
\fBNote:\fP
.RS 4
Speed from GPS is in knots, use \fBTM_GPS_ConvertSpeed()\fP to convert to useable value 
.RE
.PP

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_GPS_Speed_KilometerPerSecond \fP\fP
Convert speed to kilo meters per second 
.TP
\fB\fITM_GPS_Speed_MeterPerSecond \fP\fP
Convert speed to meters per second 
.TP
\fB\fITM_GPS_Speed_KilometerPerHour \fP\fP
Convert speed to kilo meters per hour 
.TP
\fB\fITM_GPS_Speed_MeterPerMinute \fP\fP
Convert speed to meter per minute 
.TP
\fB\fITM_GPS_Speed_MilePerSecond \fP\fP
Convert speed to miles per second 
.TP
\fB\fITM_GPS_Speed_MilePerHour \fP\fP
Convert speed to miles per hour 
.TP
\fB\fITM_GPS_Speed_FootPerSecond \fP\fP
Convert speed to foots per second 
.TP
\fB\fITM_GPS_Speed_FootPerMinute \fP\fP
Convert speed to foots per minute 
.TP
\fB\fITM_GPS_Speed_MinutePerKilometer \fP\fP
Convert speed to minutes per kilo meter 
.TP
\fB\fITM_GPS_Speed_SecondPerKilometer \fP\fP
Convert speed to seconds per kilo meter 
.TP
\fB\fITM_GPS_Speed_SecondPer100Meters \fP\fP
Convert speed to seconds per 100 meters 
.TP
\fB\fITM_GPS_Speed_MinutePerMile \fP\fP
Convert speed to minutes per mile 
.TP
\fB\fITM_GPS_Speed_SecondPerMile \fP\fP
Convert speed to seconds per mile 
.TP
\fB\fITM_GPS_Speed_SecondPer100Yards \fP\fP
Convert speed to seconds per 100 yards 
.TP
\fB\fITM_GPS_Speed_SeaMilePerHour \fP\fP
Convert speed to sea miles per hour 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
