.TH "TM_GPIO_Macros" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPIO_Macros \- TM_GPIO_Macros
.PP
GPIO Library macros\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBGPIO_PIN_0\fP   ((uint16_t)0x0001)"
.br
.RI "\fIGPIO Pins declarations\&. \fP"
.ti -1c
.RI "#define \fBGPIO_PIN_1\fP   ((uint16_t)0x0002)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_2\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_3\fP   ((uint16_t)0x0008)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_4\fP   ((uint16_t)0x0010)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_5\fP   ((uint16_t)0x0020)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_6\fP   ((uint16_t)0x0040)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_7\fP   ((uint16_t)0x0080)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_8\fP   ((uint16_t)0x0100)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_9\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_10\fP   ((uint16_t)0x0400)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_11\fP   ((uint16_t)0x0800)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_12\fP   ((uint16_t)0x1000)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_13\fP   ((uint16_t)0x2000)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_14\fP   ((uint16_t)0x4000)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_15\fP   ((uint16_t)0x8000)"
.br
.ti -1c
.RI "#define \fBGPIO_PIN_ALL\fP   ((uint16_t)0xFFFF)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_0\fP   ((uint16_t)0x0001)"
.br
.RI "\fIGPIO Pins declarations\&. \fP"
.ti -1c
.RI "#define \fBGPIO_Pin_1\fP   ((uint16_t)0x0002)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_2\fP   ((uint16_t)0x0004)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_3\fP   ((uint16_t)0x0008)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_4\fP   ((uint16_t)0x0010)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_5\fP   ((uint16_t)0x0020)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_6\fP   ((uint16_t)0x0040)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_7\fP   ((uint16_t)0x0080)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_8\fP   ((uint16_t)0x0100)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_9\fP   ((uint16_t)0x0200)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_10\fP   ((uint16_t)0x0400)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_11\fP   ((uint16_t)0x0800)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_12\fP   ((uint16_t)0x1000)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_13\fP   ((uint16_t)0x2000)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_14\fP   ((uint16_t)0x4000)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_15\fP   ((uint16_t)0x8000)"
.br
.ti -1c
.RI "#define \fBGPIO_Pin_All\fP   ((uint16_t)0xFFFF)"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPIO Library macros\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#define GPIO_PIN_0   ((uint16_t)0x0001)"

.PP
GPIO Pins declarations\&. 
.PP
\fBNote:\fP
.RS 4
For HAL drivers compatibility 
.RE
.PP

.SS "#define GPIO_Pin_0   ((uint16_t)0x0001)"

.PP
GPIO Pins declarations\&. 
.PP
\fBNote:\fP
.RS 4
For STD Periph drivers compatibility 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
