.TH "TM_GPS_Time_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPS_Time_t \- Time structure for GPS\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_gps\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBHours\fP"
.br
.ti -1c
.RI "uint8_t \fBMinutes\fP"
.br
.ti -1c
.RI "uint8_t \fBSeconds\fP"
.br
.ti -1c
.RI "uint8_t \fBHundredths\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Time structure for GPS\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t Hours"
Hours from GPS time\&. 
.SS "uint8_t Hundredths"
Hundredths from GPS time\&. 
.SS "uint8_t Minutes"
Minutes from GPS time\&. 
.SS "uint8_t Seconds"
Seconds from GPS time\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
