.TH "TM_GPS_Data_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPS_Data_t \- Main GPS data structure\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_gps\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBLatitude\fP"
.br
.ti -1c
.RI "float \fBLongitude\fP"
.br
.ti -1c
.RI "uint8_t \fBSatellites\fP"
.br
.ti -1c
.RI "uint8_t \fBFix\fP"
.br
.ti -1c
.RI "float \fBAltitude\fP"
.br
.ti -1c
.RI "\fBTM_GPS_Time_t\fP \fBTime\fP"
.br
.ti -1c
.RI "\fBTM_GPS_Date_t\fP \fBDate\fP"
.br
.ti -1c
.RI "float \fBSpeed\fP"
.br
.ti -1c
.RI "uint8_t \fBValidity\fP"
.br
.ti -1c
.RI "float \fBDirection\fP"
.br
.ti -1c
.RI "float \fBHDOP\fP"
.br
.ti -1c
.RI "float \fBPDOP\fP"
.br
.ti -1c
.RI "float \fBVDOP\fP"
.br
.ti -1c
.RI "uint8_t \fBFixMode\fP"
.br
.ti -1c
.RI "uint8_t \fBSatelliteIDs\fP [12]"
.br
.ti -1c
.RI "uint8_t \fBSatellitesInView\fP"
.br
.ti -1c
.RI "\fBTM_GPS_Result_t\fP \fBStatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main GPS data structure\&. 
.SH "Field Documentation"
.PP 
.SS "float Altitude"
Altitude above the sea\&. 
.SS "\fBTM_GPS_Date_t\fP Date"
Current data from GPS\&. \fBTM_GPS_Date_t\fP\&. 
.SS "float Direction"
Course on the ground in relation to North\&. 
.SS "uint8_t Fix"
GPS fix; 0: Invalid; 1: GPS Fix; 2: DGPS Fix\&. 
.SS "uint8_t FixMode"
Current fix mode in use:; 1: Fix not available; 2: 2D; 3: 3D\&. 
.SS "float HDOP"
Horizontal dilution of precision\&. 
.SS "float Latitude"
Latitude position from GPS, -90 to 90 degrees response\&. 
.SS "float Longitude"
Longitude position from GPS, -180 to 180 degrees response\&. 
.SS "float PDOP"
Position dilution od precision\&. 
.SS "uint8_t SatelliteIDs[12]"
Array with IDs of satellites in use\&. Only first data are valid, so if you have 5 satellites in use, only SatelliteIDs[4:0] are valid 
.SS "uint8_t Satellites"
Number of satellites in use for GPS position\&. 
.SS "uint8_t SatellitesInView"
Number of satellites in view 
.SS "float Speed"
Speed in knots from GPS\&. 
.SS "\fBTM_GPS_Result_t\fP Status"
GPS result\&. This parameter is value of \fBTM_GPS_Result_t\fP 
.SS "\fBTM_GPS_Time_t\fP Time"
Current time from GPS\&. \fBTM_GPS_Time_t\fP\&. 
.SS "uint8_t Validity"
GPS validation; 1: valid; 0: invalid\&. 
.SS "float VDOP"
Vertical dilution of precision\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
