.TH "TM_GPIO_Typedefs" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPIO_Typedefs \- TM_GPIO_Typedefs
.PP
GPIO Typedefs used for GPIO library for initialization purposes\&.  

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTM_GPIO_Mode_t\fP { \fBTM_GPIO_Mode_IN\fP = 0x00, \fBTM_GPIO_Mode_OUT\fP = 0x01, \fBTM_GPIO_Mode_AF\fP = 0x02, \fBTM_GPIO_Mode_AN\fP = 0x03 }"
.br
.RI "\fIGPIO Mode enumeration\&. \fP"
.ti -1c
.RI "enum \fBTM_GPIO_OType_t\fP { \fBTM_GPIO_OType_PP\fP = 0x00, \fBTM_GPIO_OType_OD\fP = 0x01 }"
.br
.RI "\fIGPIO Output type\&. \fP"
.ti -1c
.RI "enum \fBTM_GPIO_Speed_t\fP { \fBTM_GPIO_Speed_Low\fP = 0x00, \fBTM_GPIO_Speed_Medium\fP = 0x01, \fBTM_GPIO_Speed_Fast\fP = 0x02, \fBTM_GPIO_Speed_High\fP = 0x03 }"
.br
.RI "\fIGPIO Speed\&. \fP"
.ti -1c
.RI "enum \fBTM_GPIO_PuPd_t\fP { \fBTM_GPIO_PuPd_NOPULL\fP = 0x00, \fBTM_GPIO_PuPd_UP\fP = 0x01, \fBTM_GPIO_PuPd_DOWN\fP = 0x02 }"
.br
.RI "\fIGPIO pull resistors enumeration\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
GPIO Typedefs used for GPIO library for initialization purposes\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTM_GPIO_Mode_t\fP"

.PP
GPIO Mode enumeration\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_GPIO_Mode_IN \fP\fP
GPIO Pin as General Purpose Input 
.TP
\fB\fITM_GPIO_Mode_OUT \fP\fP
GPIO Pin as General Purpose Output 
.TP
\fB\fITM_GPIO_Mode_AF \fP\fP
GPIO Pin as Alternate Function 
.TP
\fB\fITM_GPIO_Mode_AN \fP\fP
GPIO Pin as Analog 
.SS "enum \fBTM_GPIO_OType_t\fP"

.PP
GPIO Output type\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_GPIO_OType_PP \fP\fP
GPIO Output Type Push-Pull 
.TP
\fB\fITM_GPIO_OType_OD \fP\fP
GPIO Output Type Open-Drain 
.SS "enum \fBTM_GPIO_PuPd_t\fP"

.PP
GPIO pull resistors enumeration\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_GPIO_PuPd_NOPULL \fP\fP
No pull resistor 
.TP
\fB\fITM_GPIO_PuPd_UP \fP\fP
Pull up resistor enabled 
.TP
\fB\fITM_GPIO_PuPd_DOWN \fP\fP
Pull down resistor enabled 
.SS "enum \fBTM_GPIO_Speed_t\fP"

.PP
GPIO Speed\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_GPIO_Speed_Low \fP\fP
GPIO Speed Low 
.TP
\fB\fITM_GPIO_Speed_Medium \fP\fP
GPIO Speed Medium 
.TP
\fB\fITM_GPIO_Speed_Fast \fP\fP
GPIO Speed Fast 
.TP
\fB\fITM_GPIO_Speed_High \fP\fP
GPIO Speed High 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
