.TH "TM_GPS_Distance_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPS_Distance_t \- GPS Distance and bearing struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_gps\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "float \fBLatitude1\fP"
.br
.ti -1c
.RI "float \fBLongitude1\fP"
.br
.ti -1c
.RI "float \fBLatitude2\fP"
.br
.ti -1c
.RI "float \fBLongitude2\fP"
.br
.ti -1c
.RI "float \fBDistance\fP"
.br
.ti -1c
.RI "float \fBBearing\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
GPS Distance and bearing struct\&. 
.SH "Field Documentation"
.PP 
.SS "float Bearing"
Bearing from start to stop point according to North\&. 
.SS "float Distance"
Distance between 2 points which will be calculated\&. 
.SS "float Latitude1"
Latitude of starting point\&. 
.SS "float Latitude2"
Latitude of ending point\&. 
.SS "float Longitude1"
Longitude of starting point\&. 
.SS "float Longitude2"
Longitude of ending point\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
