.TH "TM_GPS_Date_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GPS_Date_t \- Date struct for GPS date\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_gps\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBDate\fP"
.br
.ti -1c
.RI "uint8_t \fBMonth\fP"
.br
.ti -1c
.RI "uint8_t \fBYear\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Date struct for GPS date\&. 
.SH "Field Documentation"
.PP 
.SS "uint8_t Date"
Date in month from GPS\&. 
.SS "uint8_t Month"
Month from GPS\&. 
.SS "uint8_t Year"
Year from GPS\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
