.TH "TM_GRAPHIC_Options_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_GRAPHIC_Options_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_graphic\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBDefaultWidth\fP"
.br
.ti -1c
.RI "uint16_t \fBDefaultHeight\fP"
.br
.ti -1c
.RI "uint32_t \fBPixelsCount\fP"
.br
.ti -1c
.RI "uint16_t \fBWidth\fP"
.br
.ti -1c
.RI "uint16_t \fBHeight\fP"
.br
.ti -1c
.RI "TM_GRAPHIC_Orientation_t \fBOrientation\fP"
.br
.ti -1c
.RI "TM_GRAPHIC_PortLand_t \fBPortLand\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
LCD options
.PP
Parameters:
.IP "\(bu" 2
uint16_t DefaultWidth Default LCD width\&. Default width is less than default height, LCD is in portrait mode
.IP "\(bu" 2
uint16_t DefaultHeight Default LCD height\&. Default height is greater than default width, LCD is in portrait mode
.IP "\(bu" 2
uint16_t PixelsCount Number of pixels on LCD
.IP "\(bu" 2
uint16_t Width Current width, it is changed if you change LCD orientation
.IP "\(bu" 2
uint16_t Height Current height, it is changed if you change LCD orientation
.IP "\(bu" 2
TM_GRAPHIC_Orientation_t Orientation LCD Orientation\&. Value is member of TM_GRAPHIC_Orientation_t enumeration
.IP "\(bu" 2
TM_GRAPHIC_PortLand_t PortLand Only portrait or landscape mode\&. Value is member of TM_GRAPHIC_PortLand_t enumeration 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
