.TH "TM_HD44780_Options_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_HD44780_Options_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBDisplayControl\fP"
.br
.ti -1c
.RI "uint8_t \fBDisplayFunction\fP"
.br
.ti -1c
.RI "uint8_t \fBDisplayMode\fP"
.br
.ti -1c
.RI "uint8_t \fBRows\fP"
.br
.ti -1c
.RI "uint8_t \fBCols\fP"
.br
.ti -1c
.RI "uint8_t \fBcurrentX\fP"
.br
.ti -1c
.RI "uint8_t \fBcurrentY\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
