.TH "TM_ILI931_Options_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_ILI931_Options_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_ili9341\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.ti -1c
.RI "uint16_t \fBheight\fP"
.br
.ti -1c
.RI "TM_ILI9341_Orientation \fBorientation\fP"
.br
.ti -1c
.RI "uint16_t \fBWidth\fP"
.br
.ti -1c
.RI "uint16_t \fBHeight\fP"
.br
.ti -1c
.RI "TM_ILI9341_Orientation \fBOrientation\fP"
.br
.ti -1c
.RI "uint8_t \fBCurrentLayer\fP"
.br
.ti -1c
.RI "uint32_t \fBCurrentLayerOffset\fP"
.br
.ti -1c
.RI "uint8_t \fBLayer1Opacity\fP"
.br
.ti -1c
.RI "uint8_t \fBLayer2Opacity\fP"
.br
.ti -1c
.RI "TM_ILI9341_Orientation_t \fBOrient\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
LCD options Used private 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
