.TH "TM_INT_DMA2D_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_INT_DMA2D_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBWidth\fP"
.br
.ti -1c
.RI "uint16_t \fBHeight\fP"
.br
.ti -1c
.RI "uint16_t \fBCurrentWidth\fP"
.br
.ti -1c
.RI "uint16_t \fBCurrentHeight\fP"
.br
.ti -1c
.RI "uint32_t \fBStartAddress\fP"
.br
.ti -1c
.RI "uint32_t \fBOffset\fP"
.br
.ti -1c
.RI "uint32_t \fBPixels\fP"
.br
.ti -1c
.RI "uint8_t \fBInitialized\fP"
.br
.ti -1c
.RI "uint8_t \fBOrientation\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
