.TH "TM_ID" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_ID \- TM_ID
.PP
Identification library and flash size for STM32F4xx - http://stm32f4-discovery.com/2014/12/library-44-stm32f4-unique-id-and-flash-size\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTM_ID_Macros\fP"
.br
.RI "\fILibrary defines\&. \fP"
.ti -1c
.RI "\fBTM_ID_Functions\fP"
.br
.RI "\fILibrary Functions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Identification library and flash size for STM32F4xx - http://stm32f4-discovery.com/2014/12/library-44-stm32f4-unique-id-and-flash-size\&. 


.PP
\fBThis library allows you to read following things:\fP
.RS 4

.IP "\(bu" 2
Device's 96bit unique ID
.IP "\(bu" 2
Device signature
.IP "\(bu" 2
Revision
.IP "\(bu" 2
Flash size
.PP
.RE
.PP
\fBRevisions possible:\fP
.RS 4

.IP "\(bu" 2
0x1000: Revision A
.IP "\(bu" 2
0x1001: Revision Z
.IP "\(bu" 2
0x1003: Revision Y
.IP "\(bu" 2
0x1007: Revision 1
.IP "\(bu" 2
0x2001: Revision 3
.PP
.RE
.PP
\fBDevice signatures:\fP
.RS 4

.IP "\(bu" 2
0x0413: STM32F405xx/07xx and STM32F415xx/17xx)
.IP "\(bu" 2
0x0419: STM32F42xxx and STM32F43xxx
.IP "\(bu" 2
0x0423: STM32F401xB/C
.IP "\(bu" 2
0x0433: STM32F401xD/E
.IP "\(bu" 2
0x0431: STM32F411xC/E
.PP
.RE
.PP
\fBFlash size:\fP
.RS 4

.IP "\(bu" 2
Device has stored value of flash size in kB
.PP
.RE
.PP
\fBChangelog\fP
.RS 4

.RE
.PP
.PP
.nf
 Version 1.0
   - First release
.fi
.PP
.PP
\fBDependencies\fP
.RS 4

.RE
.PP
.PP
.nf
 - STM32F4xx
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
