.TH "TM_ILI9341_Button_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_ILI9341_Button_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_ili9341_button\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBx\fP"
.br
.ti -1c
.RI "uint16_t \fBy\fP"
.br
.ti -1c
.RI "uint16_t \fBwidth\fP"
.br
.ti -1c
.RI "uint16_t \fBheight\fP"
.br
.ti -1c
.RI "uint16_t \fBbackground\fP"
.br
.ti -1c
.RI "uint16_t \fBborderColor\fP"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.ti -1c
.RI "char * \fBlabel\fP"
.br
.ti -1c
.RI "\fBTM_FontDef_t\fP * \fBfont\fP"
.br
.ti -1c
.RI "uint16_t \fBcolor\fP"
.br
.ti -1c
.RI "uint16_t * \fBimage\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Button options struct
.PP
Parameters:
.IP "\(bu" 2
uint16_t x: X coordinate of top left button corner
.IP "\(bu" 2
uint16_t y: Y coordinate of top left button corner
.IP "\(bu" 2
uint16_t width: button width in pixels
.IP "\(bu" 2
uint16_t height: button height in pixels
.IP "\(bu" 2
uint16_t background: 16bit background color
.IP "\(bu" 2
uint16_t borderColor: 16bit border color
.IP "\(bu" 2
uint16_t flags: Button flags
.IP "\(bu" 2
char *label: pointer to first character of label
.IP "\(bu" 2
\fBTM_FontDef_t\fP *font: pointer to font structure
.IP "\(bu" 2
uint16_t color: label color
.IP "\(bu" 2
uint16_t *image: pointer to location at first color for pixel 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
