.TH "TM_IWDG" 3 "Tue Mar 17 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_IWDG \- TM_IWDG
.PP
Independent Watchdog timer for STM32F4xx - http://stm32f4-discovery.com/2014/07/library-20-independent-watchdog-timer-on-stm32f4xx/\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTM_IWDG_Typedefs\fP"
.br
.RI "\fILibrary Typedefs\&. \fP"
.ti -1c
.RI "\fBTM_IWDG_Functions\fP"
.br
.RI "\fILibrary Functions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Independent Watchdog timer for STM32F4xx - http://stm32f4-discovery.com/2014/07/library-20-independent-watchdog-timer-on-stm32f4xx/\&. 


.PP
\fBChangelog\fP
.RS 4

.RE
.PP
.PP
.nf
 Version 1.1
  - March 10, 2015
  - Support for STD/HAL drivers

 Version 1.0
  - First release
.fi
.PP
.PP
\fBDependencies\fP
.RS 4

.RE
.PP
.PP
.nf
 - STM32F4xx
 - defines.h
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
