.TH "TM_ID_Macros" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_ID_Macros \- TM_ID_Macros
.PP
Library defines\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBID_UNIQUE_ADDRESS\fP   0x1FFF7A10"
.br
.RI "\fIUnique ID register address location\&. \fP"
.ti -1c
.RI "#define \fBID_FLASH_ADDRESS\fP   0x1FFF7A22"
.br
.RI "\fIFlash size register address\&. \fP"
.ti -1c
.RI "#define \fBID_DBGMCU_IDCODE\fP   0xE0042000"
.br
.RI "\fIDevice ID register address\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Library defines\&. 

Defines for register locations inside STM32F4xx devices 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
