.TH "TM_IWDG_Functions" 3 "Tue Mar 17 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_IWDG_Functions \- TM_IWDG_Functions
.PP
Library Functions\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "uint8_t \fBTM_WATCHDOG_Init\fP (\fBTM_WATCHDOG_Timeout_t\fP timeout)"
.br
.RI "\fIInitialize Watchdog timer\&. \fP"
.ti -1c
.RI "void \fBTM_WATCHDOG_Reset\fP (void)"
.br
.RI "\fIReset Watchdog timer\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Library Functions\&. 


.SH "Function Documentation"
.PP 
.SS "uint8_t TM_WATCHDOG_Init (\fBTM_WATCHDOG_Timeout_t\fP timeout)"

.PP
Initialize Watchdog timer\&. 
.PP
\fBNote:\fP
.RS 4
After you initialize it, you can't disable it unless reset occur\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItimeout\&.\fP Timeout value when watchdog reset happen if not reset by user\&. This parameter can be a value of \fBTM_WATCHDOG_Timeout_t\fP enumeration 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIValue\fP if system was reset because of watchdog timer
.IP "\(bu" 2
1: Reset happen because of watchdog
.IP "\(bu" 2
0: Otherwise
.PP
.RE
.PP
|---------------------------------------------------------------------- | Copyright (C) Tilen Majerle, 2014 | | This program is free software: you can redistribute it and/or modify | it under the terms of the GNU General Public License as published by | the Free Software Foundation, either version 3 of the License, or | any later version\&. | | This program is distributed in the hope that it will be useful, | but WITHOUT ANY WARRANTY; without even the implied warranty of | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the | GNU General Public License for more details\&. | | You should have received a copy of the GNU General Public License | along with this program\&. If not, see http://www.gnu.org/licenses/\&. |---------------------------------------------------------------------- 
.SS "void TM_WATCHDOG_Reset (void)"

.PP
Reset Watchdog timer\&. 
.PP
\fBNote:\fP
.RS 4
This function have to be called periodically to reset watchdog timer, or your system will reset 
.RE
.PP
\fBParameters:\fP
.RS 4
\fINone\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fINone\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
