.TH "TM_L3GD20_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_L3GD20_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_l3gd20\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int16_t \fBX\fP"
.br
.ti -1c
.RI "int16_t \fBY\fP"
.br
.ti -1c
.RI "int16_t \fBZ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main working struct
.PP
Parameters:
.IP "\(bu" 2
int16_t X X axis rotation
.IP "\(bu" 2
int16_t Y Y axis rotation
.IP "\(bu" 2
int16_t Z Z axis rotation 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
