.TH "TM_LIBNAME" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_LIBNAME \- TM_LIBNAME
.PP
Library description here\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTM_LIB_Macros\fP"
.br
.RI "\fILibrary defines\&. \fP"
.ti -1c
.RI "\fBTM_LIB_Typedefs\fP"
.br
.RI "\fILibrary Typedefs\&. \fP"
.ti -1c
.RI "\fBTM_LIB_Functions\fP"
.br
.RI "\fILibrary Functions\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Library description here\&. 


.PP
\fBChangelog\fP
.RS 4

.RE
.PP
.PP
.nf
 Version 1.0
  - First release
.fi
.PP
.PP
\fBDependencies\fP
.RS 4

.RE
.PP
.PP
.nf
 - STM32F4xx
 - STM32F4xx RCC
 - defines.h
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
