.TH "TM_NRF24L01_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_NRF24L01_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBPayloadSize\fP"
.br
.ti -1c
.RI "uint8_t \fBChannel\fP"
.br
.ti -1c
.RI "TM_NRF24L01_OutputPower_t \fBOutPwr\fP"
.br
.ti -1c
.RI "TM_NRF24L01_DataRate_t \fBDataRate\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
