.TH "TM_OneWire_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_OneWire_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_onewire\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "GPIO_TypeDef * \fBGPIOx\fP"
.br
.ti -1c
.RI "uint16_t \fBGPIO_Pin\fP"
.br
.ti -1c
.RI "uint8_t \fBLastDiscrepancy\fP"
.br
.ti -1c
.RI "uint8_t \fBLastFamilyDiscrepancy\fP"
.br
.ti -1c
.RI "uint8_t \fBLastDeviceFlag\fP"
.br
.ti -1c
.RI "uint8_t \fBROM_NO\fP [8]"
.br
.in -1c
.SH "Detailed Description"
.PP 
OneWire working struct
.PP
Parameters:
.IP "\(bu" 2
GPIO_TypeDef* GPIOx: GPIOx port to be used for I/O functions
.IP "\(bu" 2
uint16_t GPIO_Pin: GPIO Pin to be used for I/O functions
.IP "\(bu" 2
uint8_t LastDiscrepancy: Search private
.IP "\(bu" 2
uint8_t LastFamilyDiscrepancy: Search private
.IP "\(bu" 2
uint8_t LastDeviceFlag: Search private
.IP "\(bu" 2
uint8_t ROM_NO[8]: 8-bytes address of last search device 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
