.TH "TM_RTC_Macros" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_RTC_Macros \- TM_RTC_Macros
.PP
Library defines\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRTC_SYNC_PREDIV\fP   0x3FF"
.br
.ti -1c
.RI "#define \fBRTC_ASYNC_PREDIV\fP   0x1F"
.br
.ti -1c
.RI "#define \fBRTC_PRIORITY\fP   0x04"
.br
.ti -1c
.RI "#define \fBRTC_WAKEUP_SUBPRIORITY\fP   0x00"
.br
.ti -1c
.RI "#define \fBRTC_ALARM_SUBPRIORITY\fP   0x01"
.br
.in -1c
.SH "Detailed Description"
.PP 
Library defines\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
