.TH "TM_RS485_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_RS485_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_rs485\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBMyID\fP"
.br
.ti -1c
.RI "uint8_t \fBReceivedID\fP"
.br
.ti -1c
.RI "uint8_t \fBReceivedCount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
RS485 Struct
.PP
Parameters:
.IP "\(bu" 2
uint8_t MyID: Used for transmit/receive data to detect proper ID
.IP "\(bu" 2
uint8_t ReceivedID: ID from packet arrived for us
.IP "\(bu" 2
uint8_t ReceivedCount: Number of available data arrived for us 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
