.TH "TM_RE_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_RE_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_rotary_encoder\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int32_t \fBAbsolute\fP"
.br
.ti -1c
.RI "int32_t \fBDiff\fP"
.br
.ti -1c
.RI "TM_RE_Rotate_t \fBRotation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main struct
.PP
Parameters:
.IP "\(bu" 2
int32_t Absolute Absolute value of rotation from beginning of program
.PP
.PP
int32_t Diff Rotary difference from last check
.IP "\(bu" 2
TM_RE_Rotate_t Rotation It allows you to check if rotary was increased, decreased or nothing 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
