.TH "TM_STMPE811_TouchData" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_STMPE811_TouchData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_stmpe811\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBx\fP"
.br
.ti -1c
.RI "uint16_t \fBy\fP"
.br
.ti -1c
.RI "TM_STMPE811_State_t \fBpressed\fP"
.br
.ti -1c
.RI "TM_STMPE811_State_t \fBlast_pressed\fP"
.br
.ti -1c
.RI "TM_STMPE811_Orientation_t \fBorientation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct, which is passed into TM_STMPE811_ReadTouch function
.PP
Parameters:
.IP "\(bu" 2
uint16_t x: x coordinate for lcd
.IP "\(bu" 2
uint16_t y: y coordinate for lcd
.IP "\(bu" 2
TM_STMPE811_State_t pressed:
.IP "  \(bu" 4
TM_STMPE811_State_Pressed when pressed
.IP "  \(bu" 4
TM_STMPE811_State_Released when released
.PP

.IP "\(bu" 2
TM_STMPE811_State_t last_pressed:
.IP "  \(bu" 4
TM_STMPE811_State_Pressed when was pressed
.IP "  \(bu" 4
TM_STMPE811_State_Released when was released
.PP

.IP "\(bu" 2
TM_STMPE811_Orientation_t orientation: Set touch screen orientation to read 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
