.TH "TM_STM32F4xx_Libraries" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_STM32F4xx_Libraries \- TM_STM32F4xx_Libraries
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTM_DISCO\fP"
.br
.RI "\fILeds and buttons for STM32F4 Discovery, Nucleo and eval boards - http://stm32f4-discovery.com/2014/04/stm32f429-discovery-gpio-tutorial-with-onboard-leds-and-button/\&. \fP"
.ti -1c
.RI "\fBTM_GPIO\fP"
.br
.RI "\fITM GPIO Library for STM32F4xx - http://stm32f4-discovery.com/2015/03/library-53-gpio-for-stm32f4\&. \fP"
.ti -1c
.RI "\fBTM_GPS\fP"
.br
.RI "\fIGPS NMEA standard data parser for STM32F4xx devices - http://stm32f4-discovery.com/2014/08/library-27-gps-stm32f4-devices/\&. \fP"
.ti -1c
.RI "\fBTM_ID\fP"
.br
.RI "\fIIdentification library and flash size for STM32F4xx - http://stm32f4-discovery.com/2014/12/library-44-stm32f4-unique-id-and-flash-size\&. \fP"
.ti -1c
.RI "\fBTM_LIBNAME\fP"
.br
.RI "\fILibrary description here\&. \fP"
.ti -1c
.RI "\fBTM_LOWPOWER\fP"
.br
.RI "\fILow power library for STM32F4xx devices - http://stm32f4-discovery.com/2014/10/library-39-power-consumption-modes-for-stm32f4\&. \fP"
.ti -1c
.RI "\fBTM_RTC\fP"
.br
.RI "\fIRTC Library for STM32F4xx devices - http://stm32f4-discovery.com/2014/07/library-19-use-internal-rtc-on-stm32f4xx-devices/\&. \fP"
.ti -1c
.RI "\fBTM_USART\fP"
.br
.RI "\fITM USART Library for STM32F4xx - http://stm32f4-discovery.com/2014/04/library-04-connect-stm32f429-discovery-to-computer-with-usart/\&. \fP"
.ti -1c
.RI "\fBTM_WATCHDOG\fP"
.br
.RI "\fIIndependent Watchdog timer for STM32F4xx - http://stm32f4-discovery.com/2014/07/library-20-independent-watchdog-timer-on-stm32f4xx/\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
