.TH "TM_TIMER_PROPERTIES_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_TIMER_PROPERTIES_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_timer_properties\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBTimerFrequency\fP"
.br
.ti -1c
.RI "uint32_t \fBMaxPeriod\fP"
.br
.ti -1c
.RI "uint32_t \fBMaxPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBPeriod\fP"
.br
.ti -1c
.RI "uint32_t \fBPrescaler\fP"
.br
.ti -1c
.RI "uint32_t \fBFrequency\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct for timer data
.PP
Parameters:
.IP "\(bu" 2
uint32_t TimerFrequency: timer's working frequency
.IP "\(bu" 2
uint32_t MaxPeriod: Max timer period
.IP "\(bu" 2
uint32_t MaxPrescaler: Max timer prescaler
.IP "\(bu" 2
uint32_t Period: Timer's working period
.IP "\(bu" 2
uint32_t Prescaler: Timer's working prescaler
.IP "\(bu" 2
uint32_t Frequency: Timer's reload frequency 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
