.TH "TM_USART_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_USART_t \- Internal USART struct\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBBuffer\fP"
.br
.ti -1c
.RI "uint16_t \fBSize\fP"
.br
.ti -1c
.RI "uint16_t \fBNum\fP"
.br
.ti -1c
.RI "uint16_t \fBIn\fP"
.br
.ti -1c
.RI "uint16_t \fBOut\fP"
.br
.ti -1c
.RI "uint8_t \fBInitialized\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Internal USART struct\&. 

|---------------------------------------------------------------------- | Copyright (C) Tilen Majerle, 2014 | | This program is free software: you can redistribute it and/or modify | it under the terms of the GNU General Public License as published by | the Free Software Foundation, either version 3 of the License, or | any later version\&. | | This program is distributed in the hope that it will be useful, | but WITHOUT ANY WARRANTY; without even the implied warranty of | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE\&. See the | GNU General Public License for more details\&. | | You should have received a copy of the GNU General Public License | along with this program\&. If not, see http://www.gnu.org/licenses/\&. |---------------------------------------------------------------------- 

.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
