.TH "TM_USART_Macros" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_USART_Macros \- TM_USART_Macros
.PP
USART default values for defines\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTM_USART_BUFFER_SIZE\fP   32"
.br
.ti -1c
.RI "#define \fBTM_USART1_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_USART2_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_USART3_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_UART4_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_UART5_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_USART6_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_UART7_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_UART8_BUFFER_SIZE\fP   TM_USART_BUFFER_SIZE"
.br
.ti -1c
.RI "#define \fBTM_USART_NVIC_PRIORITY\fP   0x06"
.br
.ti -1c
.RI "#define \fBTM_USART1_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_USART1_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_USART1_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_USART1_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_USART1_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_USART2_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_USART2_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_USART2_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_USART2_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_USART2_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_USART3_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_USART3_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_USART3_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_USART3_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_USART3_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_UART4_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_UART4_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_UART4_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_UART4_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_UART4_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_UART5_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_UART5_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_UART5_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_UART5_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_UART5_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_USART6_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_USART6_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_USART6_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_USART6_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_USART6_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_UART7_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_UART7_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_UART7_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_UART7_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_UART7_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.ti -1c
.RI "#define \fBTM_UART8_HARDWARE_FLOW_CONTROL\fP   USART_HardwareFlowControl_None"
.br
.ti -1c
.RI "#define \fBTM_UART8_MODE\fP   USART_Mode_Tx | USART_Mode_Rx"
.br
.ti -1c
.RI "#define \fBTM_UART8_PARITY\fP   USART_Parity_No"
.br
.ti -1c
.RI "#define \fBTM_UART8_STOP_BITS\fP   USART_StopBits_1"
.br
.ti -1c
.RI "#define \fBTM_UART8_WORD_LENGTH\fP   USART_WordLength_8b"
.br
.in -1c
.SH "Detailed Description"
.PP 
USART default values for defines\&. 

All values can be overwritten in your project's defines\&.h file\&.
.PP
Do this only in case you know what are you doing\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
