.TH "TM_USB_HIDDEVICE_Gamepad_t" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_USB_HIDDEVICE_Gamepad_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tm_stm32f4_usb_hid_device\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton1\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton2\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton3\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton4\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton5\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton6\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton7\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton8\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton9\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton10\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton11\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton12\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton13\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton14\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton15\fP"
.br
.ti -1c
.RI "TM_USB_HIDDEVICE_Button_t \fBButton16\fP"
.br
.ti -1c
.RI "int8_t \fBLeftXAxis\fP"
.br
.ti -1c
.RI "int8_t \fBLeftYAxis\fP"
.br
.ti -1c
.RI "int8_t \fBRightXAxis\fP"
.br
.ti -1c
.RI "int8_t \fBRightYAxis\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Gamepad struct for 2 gamepads available
.PP
Parameters:
.IP "\(bu" 2
TM_USB_HIDDEVICE_Button_t Button[1:16]: Set value, according to if button on your project is pressed Gamepad supports 16 buttons
.IP "\(bu" 2
int8_t LeftXAxis: Left joystick X axis
.IP "\(bu" 2
int8_t LeftYAxis: Left joystick Y axis
.IP "\(bu" 2
int8_t RightXAxis: Right joystick Y axis
.IP "\(bu" 2
int8_t RightYAxis: Right joystick Y axis 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
