.TH "TM_WATCHDOG_Typedefs" 3 "Wed Mar 18 2015" "Version v1.0.0" "TM STM32F4xx Libraries" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TM_WATCHDOG_Typedefs \- TM_WATCHDOG_Typedefs
.PP
Library Typedefs\&.  

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTM_WATCHDOG_Timeout_t\fP { \fBTM_WATCHDOG_Timeout_5ms\fP, \fBTM_WATCHDOG_Timeout_10ms\fP, \fBTM_WATCHDOG_Timeout_15ms\fP, \fBTM_WATCHDOG_Timeout_30ms\fP, \fBTM_WATCHDOG_Timeout_60ms\fP, \fBTM_WATCHDOG_Timeout_120ms\fP, \fBTM_WATCHDOG_Timeout_250ms\fP, \fBTM_WATCHDOG_Timeout_500ms\fP, \fBTM_WATCHDOG_Timeout_1s\fP, \fBTM_WATCHDOG_Timeout_2s\fP, \fBTM_WATCHDOG_Timeout_4s\fP }"
.br
.RI "\fIWatchdog timeout settings\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Library Typedefs\&. 


.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBTM_WATCHDOG_Timeout_t\fP"

.PP
Watchdog timeout settings\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITM_WATCHDOG_Timeout_5ms \fP\fP
System reset called every 5ms 
.TP
\fB\fITM_WATCHDOG_Timeout_10ms \fP\fP
System reset called every 10ms 
.TP
\fB\fITM_WATCHDOG_Timeout_15ms \fP\fP
System reset called every 15ms 
.TP
\fB\fITM_WATCHDOG_Timeout_30ms \fP\fP
System reset called every 30ms 
.TP
\fB\fITM_WATCHDOG_Timeout_60ms \fP\fP
System reset called every 60ms 
.TP
\fB\fITM_WATCHDOG_Timeout_120ms \fP\fP
System reset called every 120ms 
.TP
\fB\fITM_WATCHDOG_Timeout_250ms \fP\fP
System reset called every 250ms 
.TP
\fB\fITM_WATCHDOG_Timeout_500ms \fP\fP
System reset called every 500ms 
.TP
\fB\fITM_WATCHDOG_Timeout_1s \fP\fP
System reset called every 1s 
.TP
\fB\fITM_WATCHDOG_Timeout_2s \fP\fP
System reset called every 2s 
.TP
\fB\fITM_WATCHDOG_Timeout_4s \fP\fP
System reset called every 4s 
.SH "Author"
.PP 
Generated automatically by Doxygen for TM STM32F4xx Libraries from the source code\&.
